version: "3.2"
services:
  net_machine:
    image: alpine
    container_name:  net_machine
    command: echo "installed networks"
    restart: always
    networks:
      bsides_net:

networks:
  bsides_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.10.100.0/16