name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:11
        env:
          POSTGRES_DB: billing_bsides_db
          POSTGRES_USER: bsides
          POSTGRES_PASSWORD: bsides
          VIRTUAL_HOST: iron-psql.localhost
        #ports:
        #  - 54322:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Create .env LARAVEL_CONTENT_ENV
      run: php -r "file_exists('.env') || copy('.env.example-old', '.env');"
      #run: php -r "file_put_contents('.env', '${{ secrets.LARAVEL_CONTENT_ENV }}');"
    ##- name: Install Docker networks
    ##  run: docker-compose -f .github/actions/docker-compose-github-network.yml up -d --build
    ##- name: Create Docker PostgreSql
    ##  run: php -r "file_put_contents('.github/actions/docker-compose-github-pgsql.yml', '${{ secrets.DOCKER_COMPOSE_YML }}');"
    ##- name: Show Files
    ##  run: cat .github/actions/docker-compose-github-pgsql.yml 
    ##- name: Install Docker PostgreSql
    ##  run: docker-compose -f .github/actions/docker-compose-github-pgsql.yml up -d --build
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Docker show 
      run: docker ps 
    #- name: Generate key
    #  run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage #bootstrap/cache
    - name: Create Database
      run: php artisan migrate
    #  run: |
    #    mkdir -p database
    #    touch database/database.sqlite
    #- name: Execute tests (Unit and Feature tests) via PHPUnit
    #  env:
    #    #DB_CONNECTION: sqlite
    #    #DB_DATABASE: database/database.sqlite
    #    DB_CONNECTION: pgsql  
    #    DB_HOST: 10.10.1.0.3
    #    DB_PORT: 5432
    #    DB_DATABASE: billing_bsides_db
    #    DB_USERNAME: bsides
    #    DB_PASSWORD: '#-bs1dEsP&%.' 
    #  run: vendor/bin/phpunit
       
