name: CI/CD DevSecOps BSides Lumen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lumen-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4, 8.0]

    name: TEST - PHP ${{ matrix.php }}

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: ${{secrets.LUMEN_DATABASE_DB}}
          POSTGRES_USER: ${{ secrets.LUMEN_DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.LUMEN_DATABASE_PASS }}
          VIRTUAL_HOST: iron-psql.localhost
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '${{ matrix.php }}'
    - uses: actions/checkout@v2

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}

    - name: Create .env LARAVEL_CONTENT_ENV
      #run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      run: php -r "file_put_contents('.env', '${{ secrets.LARAVEL_CONTENT_ENV }}');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Docker show 
      run: docker ps 
    #- name: Generate key
    #  run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage 
    - name: Create Database
      run: php artisan migrate --force
    #  run: |
    #    mkdir -p database
    #    touch database/database.sqlite
    #- name: Execute tests (Unit and Feature tests) via PHPUnit
    #  env:
    #    #DB_CONNECTION: sqlite
    #    #DB_DATABASE: database/database.sqlite
    #    DB_CONNECTION: pgsql  
    #    DB_HOST: 10.10.1.0.3
    #    DB_PORT: 5432
    #    DB_DATABASE: billing_bsides_db
    #    DB_USERNAME: bsides
    #    DB_PASSWORD: '#-bs1dEsP&%.' 
    #  run: vendor/bin/phpunit
       
